export { default as MORNING } from './../../assets/pictures/morning.jpg'
export { default as AFTER_NOON } from './../../assets/pictures/afternoon.jpg'
export { default as EVENING } from './../../assets/pictures/evening.jpg'
export { default as NIGHT } from './../../assets/pictures/night.jpg'
export { default as GLOBE } from './../../assets/pictures/globeIc.png'